apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/agent: ""
        node-role.kubernetes.io/edge: ""
      containers:
      - name: echo-server
        image: jmalloc/echo-server
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
